-- Таблица нормативов сна по возрастным группам.
-- Скрипт безопасен для повторного запуска.

begin;

create table if not exists public.sleep_norms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  age_min_months integer not null,
  age_max_months integer,

  night_min_minutes integer not null,
  night_max_minutes integer not null,
  night_label text not null,

  nap_min_minutes integer not null,
  nap_max_minutes integer not null,
  nap_label text not null,

  total_min_minutes integer not null,
  total_max_minutes integer not null,
  total_label text not null,

  interval_nap_min_minutes integer not null,
  interval_nap_max_minutes integer not null,
  interval_nap_label text not null,

  interval_before_night_min_minutes integer not null,
  interval_before_night_max_minutes integer not null,
  interval_before_night_label text not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (age_min_months >= 0),
  check (age_max_months is null or age_max_months >= age_min_months)
);

create index if not exists sleep_norms_age_range_idx
  on public.sleep_norms (age_min_months, age_max_months);

-- Триггер updated_at
create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sleep_norms_updated_at on public.sleep_norms;
create trigger trg_sleep_norms_updated_at
before update on public.sleep_norms
for each row
execute function public.set_updated_at_timestamp();

-- RLS: чтение всем авторизованным, изменение только service_role.
alter table public.sleep_norms enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'sleep_norms'
      and policyname = 'sleep_norms_select_authenticated'
  ) then
    create policy sleep_norms_select_authenticated
      on public.sleep_norms
      for select
      to authenticated
      using (true);
  end if;
end $$;

-- Заполнение стартовыми значениями
insert into public.sleep_norms (
  code,
  title,
  age_min_months,
  age_max_months,
  night_min_minutes,
  night_max_minutes,
  night_label,
  nap_min_minutes,
  nap_max_minutes,
  nap_label,
  total_min_minutes,
  total_max_minutes,
  total_label,
  interval_nap_min_minutes,
  interval_nap_max_minutes,
  interval_nap_label,
  interval_before_night_min_minutes,
  interval_before_night_max_minutes,
  interval_before_night_label
) values
  ('0_2_months', '0–2 месяца', 0, 2, 480, 540, 'норма 8–9 ч', 420, 540, 'норма 7–9 ч', 900, 1080, 'норма 15–18 ч', 45, 75, 'днём 45–75 мин', 45, 90, 'перед ночью 45–90 мин'),
  ('3_5_months', '3–5 месяцев', 3, 5, 540, 660, 'норма 9–11 ч', 240, 300, 'норма 4–5 ч', 780, 960, 'норма 13–16 ч', 75, 150, 'днём 1.25–2.5 ч', 90, 180, 'перед ночью 1.5–3 ч'),
  ('6_11_months', '6–11 месяцев', 6, 11, 540, 660, 'норма 9–11 ч', 120, 240, 'норма 2–4 ч', 720, 900, 'норма 12–15 ч', 120, 210, 'днём 2–3.5 ч', 150, 240, 'перед ночью 2.5–4 ч'),
  ('12_24_months', '12–24 месяца', 12, 24, 600, 720, 'норма 10–12 ч', 60, 180, 'норма 1–3 ч', 660, 840, 'норма 11–14 ч', 180, 300, 'днём 3–5 ч', 240, 360, 'перед ночью 4–6 ч')
on conflict (code) do update set
  title = excluded.title,
  age_min_months = excluded.age_min_months,
  age_max_months = excluded.age_max_months,
  night_min_minutes = excluded.night_min_minutes,
  night_max_minutes = excluded.night_max_minutes,
  night_label = excluded.night_label,
  nap_min_minutes = excluded.nap_min_minutes,
  nap_max_minutes = excluded.nap_max_minutes,
  nap_label = excluded.nap_label,
  total_min_minutes = excluded.total_min_minutes,
  total_max_minutes = excluded.total_max_minutes,
  total_label = excluded.total_label,
  interval_nap_min_minutes = excluded.interval_nap_min_minutes,
  interval_nap_max_minutes = excluded.interval_nap_max_minutes,
  interval_nap_label = excluded.interval_nap_label,
  interval_before_night_min_minutes = excluded.interval_before_night_min_minutes,
  interval_before_night_max_minutes = excluded.interval_before_night_max_minutes,
  interval_before_night_label = excluded.interval_before_night_label,
  updated_at = now();

commit;
